### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1209]
Releases:

- [x] Bump package versions
- [x] Create compiler tag
- [x] Create binaries
- [x] Pursuit 2
- [x] Try PureScript
- [x] Blog post `http://www.purescript.org/learn/getting-started/`
- [x] Release 0.7.1 for bug fixes

Documentation: 
- [x] Write release notes
- [x] Finish migration guide
- [x] Add note to book about compatibility

Testing:

- [x] `core-tests`

Tools:

- [x] Pulp
- [ ] `grunt-purescript`
- [x] `gulp-purescript`
- [ ] `psc-release`
- [x] `purs-loader`

Distributions:

- [ ] Chocolatey
- [x] `npm`
- [x] `brew`
- [x] AUR
- [x] Hackage

Did I miss anything?

/cc @garyb @ethul @joneshf @hdgarrood @alexchandel @mechairoi

**Comment by ethul** [comment]
There is also the [purs-loader](https://github.com/ethul/purs-loader) tool for using PureScript with Webpack

**Comment by hdgarrood** [comment]
Actually, come to think of it, it's difficult to test cross-package links in the documentation right now (we can't handle versions like `0.3.0-rc.1`, for example). I still think a usable version of Pursuit is possible very soon, but can it wait until after the release of 0.7.0?

**Comment by paf31** [comment]
@hdgarrood Of course, no rush. I'd just like to be able to document the new modules, since Pursuit 1 will break at some point, if not updated (when Linode next restarts our box).

**Comment by joneshf** [comment]
I started trying to update the aur binary package this morning, but ran into an error about Insecure RPATH, so I'll look into it more tomorrow.

**Comment by garyb** [comment]
re: `0.7.0.1`, I thought we weren't doing that anymore, as it's semver incompatible?

**Comment by paf31** [comment]
Ah right, true.

**Comment by paf31** [comment]
`0.7.1` is fine I assume?

**Comment by garyb** [comment]
Yep, that's totally fine.

**Comment by garyb** [comment]
Actually `0.7.0.1` might be fine in this case, as it's just a release for cabal isn't it?

**Comment by paf31** [comment]
Yes, so I assumed we would use PVP for Hackage and semver for libraries?

**Comment by garyb** [comment]
The problem was when we released `0.6.9.x` we had to start making up different versions for the `npm` package - the current version on there is `0.6.10`. I think we have enough problems with version confusion that it would be preferrable to keep the versions linked if we can :wink:

**Comment by hdgarrood** [comment]
I think that if you follow the rules of semver, then although it's not quite in the spirit of the PVP, it's still compliant with the PVP. For example, semver mandates that backwards-compatible bug fixes bump the third version component; PVP expects you to leave the first three alone and bump the fourth in this case, but doesn't go as far as forbidding you from bumping the third component. So I think using semver on Hackage would be fine. Having npm and the actual binaries disagree about their versions seems more dangerous to me.

**Comment by paf31** [comment]
@hdgarrood I've uploaded docs for all of the libraries which I know are on 0.7 and tagged, so I'll mark Pursuit 2 as done.

**Comment by ethul** [comment]
gulp-purescript @ 0.5.0 has just been release with PureScript 0.7 support.

**Comment by paf31** [comment]
@ethul :+1: Thanks!

**Comment by ethul** [comment]
Welcome, thanks to @garyb too!

**Comment by joneshf** [comment]
Aur updated with 0.7.0: https://aur4.archlinux.org/packages/purescript-bin

**Comment by paf31** [comment]
@joneshf Thanks!

**Comment by ethul** [comment]
purs-loader @ 0.3.0 has just been released with PureScript 0.7 support.

**Comment by garyb** [comment]
Thanks, ticked it off!

**Comment by ethul** [comment]
@garyb Welcome!

**Comment by paf31** [comment]
The main stuff is pretty much done, and I think the remaining items have issues on their own issue trackers, so I'll close this.

That wraps up 0.7, thank you everyone! :fireworks:
