### ISSUE TITLE
Planned 0.9 Breaking Changes

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2012]
- Alias changes
  - [x] Required fixity declarations for operators
  - [x] Remove non-aliased operator declarations (require `as`) (operator names cannot be introduced by any means other than alias - no function arguments with operator names anymore)
- [x] Properly implement `Partial` constraints
- [x] Remove `qualified` keyword (#1997)
- [x] Remove legacy operator sections
- [x] `class` imports and exports
- [x] Indentation fix (#1968) 
- [x] Update for names in new prelude (#1963)
- [x] Remove `--require-path` (#1996)
- [x] Rename `Object` to `Record` (#1768)
- [x] Require modules to be imported for names to resolve (#1511)
- [x] Only allow one module per file
- [x] Find foreign modules by name rather than comment-search (#2065)
- [x] Updated behaviour of imports so only exactly things that are imported are brought into scope (part of #1901)
- [ ] <s>Syntax updates for imports? (the more controversial part of #1901 still)</s>

**Comment by garyb** [comment]
Remove non-aliased operator declarations

**Comment by paf31** [comment]
Isn't that the same as "Required fixity declarations for operators"?

**Comment by garyb** [comment]
I guess so, there are two parts to it though: requiring the `as` part of an `infix` declaration, but also removing operator parsing from declared module/class members. I'm pretty sure `Ident` can lose its `Op` constructor entirely when we do that, in fact.

**Comment by adinapoli** [comment]
Sorry so much for hijacking the thread guys (feel free to delete this comment), but is there any blogpost/manuscript/testament explaining the upcoming breaking changes and why are they necessary? Of course nobody expect for a pre 1.0 project to be stable, but at the same time those described here seems (at least without any other extra context) quite massive changes affecting virtually all the projects out there. As lots of companies (including us!) are writing PureScript for a living, I would like to try understanding how bad this is gonna impact us, and how we can react on time to not sink :grin: 

Thank you for you hard work folks!

**Comment by hdgarrood** [comment]
@adinapoli most of these changes are just removing the previously discussed and deprecated ways of doing things. Right now, there are two different ways of declaring operators, two different ways of importing and exporting type classes, two different ways of importing modules qualified, and so on. We just want to remove the worse versions of each because there's no reason to keep them, and because continuing to support them complicates the compiler and other language tooling. As of 0.8 the compiler warns you to avoid the deprecated ways anyway, so if you're heeding the warnings it won't affect you much at all. Each individual change listed here has an issue elsewhere on this issue tracker if you're interested in rationale.

**Comment by adinapoli** [comment]
Thanks folks!

We are still running the version 0.7 of the compiler, so that’s why we
haven’t been hit with those warnings.

I guess it’s time to upgrade to 0.8 then and start tackling those warning
:wink:

**Comment by garyb** [comment]
@paf31 How about disallowing multiple modules per file, requiring imports, and requiring imports to be grouped at the top of a module? Or are those things going to be pushed to a later release?

**Comment by paf31** [comment]
Obviously I'd love to see those changes go in 😄

**Comment by garyb** [comment]
Well if nothing else we should probably finally kill multiple modules per a file, we've been talking about that for 2 years now! And some 3rd party tools assume single modules too, I think.

If we're pretty sure we can get good juice out of restricting the handling of imports then it probably is worth it. Pretty much the only time I use the fully qualified import thing is for debugging, so apart from the fact you've seen me tripped up by that recently (leaving redundant imports in a PR :wink:) I wouldn't miss it.

It also resolves an ambiguity about what it means if you try and use `X.y` when `X` is both an `import M as X` as well as there being an actual `X`. I'm prettttty sure the `M as X` takes precedence and essentially hides "actual" `X`, but even I don't know for sure right now. There's a chance that if `y` is defined in acutal `X` but not in `M as X` it will take the actual one. I could go and check, but I'm just illustrating the point that it's confusing.

If we do do this, should we add #1901 to this list too? I know @AppShipIt is enthusiastic to get this in 0.9, and it seems like a sensible way to proceed.

**Comment by paf31** [comment]
Let's discuss these on IRC once 0.8.5 is released then.

**Comment by AppShipIt** [comment]
> If we do do this, should we add #1901 to this list too? I know @AppShipIt is enthusiastic to get this in 0.9, and it seems like a sensible way to proceed.

Pretty please 💗 I started to tackle it a month ago but got busy with meetup stuff. Or at least roll back #1742 and #1747 so it doesn't revert between major versions.

**Comment by hdgarrood** [comment]
I'd personally rather hold off on any breaking changes to imports until we can agree on some way of fixing the issue that two different packages can both define the same module name, and then anything that depends on both can no longer be compiled. I expect fixing this will require breaking changes too, and I think @paf31 said that he wanted to avoid breaking imports on too many separate occasions.

**Comment by AppShipIt** [comment]
> two different packages can both define the same module name,

Would that not require package awareness?

> he wanted to avoid breaking imports on too many separate occasions.

Hence my concern about #1742/#1747.

**Comment by natefaubion** [comment]
> Would that not require package awareness?

I suppose you could enforce it at the pursuit level. There's no reason a pursuit upload couldn't look at the declared namespaces and maybe offer warnings (say, a single package declares Data.* and Control.* namespaces, maybe?), or errors (there's already a package on pursuit using the namespace).

**Comment by hdgarrood** [comment]
It probably would require package awareness, but either way it's very likely to be a breaking change, and I think it's severe enough that it really needs fixing. 

I don't want to try enforcing this kind of stuff in Pursuit because right now it isn't a package registry, it's just a place to put docs. The real source of truth here is Bower, i.e. tags on github repos, and anyone can put anything there. I think we should enforce these sorts of things in the registry (so, we'd have to create our own and stop using bower) or not at all.

#1742 and #1747 don't really count because they were only in an RC release.

**Comment by AppShipIt** [comment]
> #1742 and #1747 don't really count because they were only in an RC release.

The point is they should be reverted before a major release.

**Comment by hdgarrood** [comment]
Why? There was never a non-RC release that included the (..) open import syntax, so I think it would be fine to release 0.9 before reverting them.

**Comment by AppShipIt** [comment]
> There was never a non-RC release that included the `(..)` open import syntax,

Thanks for clarification I was mistaken.

**Comment by garyb** [comment]
What was the concern? That we have `import X (..)` in some 0.8.x and then took it away again? If so, yeah, it never made it into a proper release, so there should be no issues with it being a breaking change.

**Comment by AppShipIt** [comment]
> That we have import X (..) in some 0.8.x and then took it away again?

Yeah I mistakenly thought `(..)` was introduced between major versions.

**Comment by garyb** [comment]
Ah ok, yeah, we're more careful about that kind of thing these days! :smile:

**Comment by AppShipIt** [comment]
@hdgarrood's concern makes sense to me. It pops up in surprising situations like https://github.com/purescript/purescript/issues/1901#issuecomment-191458806.

**Comment by paf31** [comment]
@garyb This can be closed now, right?

**Comment by paf31** [comment]
Did we decide we're going to change the way we find foreign modules (by name, not comment), or not? If so, we should add that to the list here as well.

**Comment by kRITZCREEK** [comment]
The [Getting Started Guide](http://www.purescript.org/learn/getting-started/) on the website will also need updating and I'd consider that a "breaking change". Do we want to track this here or in the website repo?

**Comment by garyb** [comment]
@paf31 I updated the list with a few more things that weren't tracked here. We still need to decide once and for all what we're doing about the import syntax proposal #1901, if anything. I'm all for changing the semantics though so that it's totally clear what is brought into scope by an import.

**Comment by hdgarrood** [comment]
I think everyone was happy with the proposal that instead of the comment in ffi modules, you would just have the foreign module's file name as the purescript module's file name including `.purs` plus some backend-specific extension, such as `.js`.

**Comment by paf31** [comment]
> -Require modules to be imported for names to resolve (#1511)
> - Updated behaviour of imports so only exactly things that are imported are brought into scope (part of #1901)

Are these the same thing?

I think that it's perhaps a little hasty to follow Elm's lead on imports when a large part of why Elm's approach to imports is beneficial seems to be that they don't have type classes (so a good default needs to differentiate `List.map` from `Signal.map`). I'm also not a fan of the suggestion to bring names into scope using the last segment of the module name.

So I think we should hold off on syntax changes to imports in 0.9. I don't think we're fully in agreement about what's best yet, and it's a very big change with no deprecation period. I suggest we keep 0.9 focused on changes to support the new core libraries, get those released, and then reconsider imports.

**Comment by garyb** [comment]
No, they're a little different, although conflated unless we change import syntax, since we don't have any syntax that means `import X as X` aside from writing it out explicitly.

- The first one is saying that fully qualified names will not work anymore, qualifiers need to refer to imported modules.
- The second one is a further restriction, saying if you do `import X (a)` then only the identifier `a` will be brought into scope, no `X.a`.

**Comment by hdgarrood** [comment]
I think we should add the psci changes detailed here: https://github.com/purescript/purescript/pull/2088#issuecomment-216734354

Specifically:
* `:load` and `:foreign` directives were removed from psci, now you have to pass globs on the command line
* psci no longer reloads changed modules automatically, but you can trigger a reload with the new `:reload` directive
* The `.psci` file is now ignored

**Comment by AppShipIt** [comment]
Is it being tracked anywhere that multiple reserved words (there was an issue for `do` but not `let` and `case`) can occur in the same column as a declaration?

```purs
main =
let
  hi = "Hello"
  in
    log "Hello"
```

**Comment by paf31** [comment]
Didn't you create an issue for that? I don't think that will be in 0.9 though.

**Comment by paf31** [comment]
I suggest we move the bigger import changes (#1901) to 0.10 until we agree on what to change.

**Comment by AppShipIt** [comment]
No my issue was about changing the way indentation is intended to work. That is actually a bug relative to Haskell or how I understand it's intended to work. Why not? I thought the break was relatively minor? There was a previous PR (I'm looking for it) that didn't account for the general issue or add tests.


RE: #1901 👍.

**Comment by AppShipIt** [comment]
^ #2078.

**Comment by paf31** [comment]
Sorry, I understand now what you're referring to.

**Comment by AppShipIt** [comment]
Should the second to last ckeckbox be crossed out? It sounds like it's #2131.

**Comment by paf31** [comment]
Right you are.

**Comment by paf31** [comment]
I'm going to close this, since everything is now merged. I'll create a release checklist issue for everything we need to do before 0.9 proper.
