### ISSUE TITLE
0.9.1 Release Checklist

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2151]
- Libraries
  - [x] Core
  - [x] Contrib
  - [x] `purescript-node`
  - [x] Update Pursuit and migrate data
- Documentation 
  - [x] Update existing website articles
  - [x] Release notes
  - [x] Blog post
  - [x] Update book
- Testing
  - [x] Run `core-tests`
  - Manual testing for 
    - [x] `psci`
    - [x] `psc-ide-server`
    - [x] `psc-publish`
- Releases
  - [x] Compiler binary release
  - [x] Compiler NPM release
  - [x] Try PureScript
- Tools
  - [x] Pulp
  - [x] Gulp
  - [x] Webpack tools
  - [x] Editor plugins

Did I miss anything? I suspect there are some tools which need to be added here, and it would be useful to create that list.

/cc @garyb @hdgarrood @ethul @kRITZCREEK

**Comment by hdgarrood** [comment]
That all looks sensible to me, I can't think of anything that has been missed. I have been using the code in https://github.com/bodil/pulp/pull/212/files locally with code from 0.9 for the last couple of days and it seems ok. I'm going to wait for an 0.9.0 RC for the compiler and then test it more thoroughly then.

**Comment by paf31** [comment]
Release notes first draft (feel free to edit):

## Breaking Changes

- Error on missing Partial constraint (@paf31, @garyb)
- Require imports to appear before other declarations (@paf31)
- Remove support for `=` in object binders (@paf31)
- Only allow one module per file (@garyb)
- Name resolving (@garyb)
- Find foreign modules by name rather than comment-search (@paf31)
- Rename Prim.Object to Prim.Record, fix #1768 (@paf31)
- 0.9 Remove deprecated class import/export syntax (@LiamGoodacre)

## Enhancements

- Typed hole errors now include environment information (#2070, @paf31)
- [psc-ide] Cache last rebuild (@kRITZCREEK)
- [psc-ide] adds a reset command (@kRITZCREEK)
- Type suggestions (@nwolverson)
- PSCi speed improvements and design changes (@paf31)
- Cache last rebuild (@kRITZCREEK)
- Improve license errors in psc-publish (@hdgarrood)
- Tighten source-spans to token end position -> 0.9 (@nwolverson)
- Type suggestions -> 0.9 (@nwolverson)

## Bug Fixes

- Fix issue 2128 (@bmjames)
- Use (..) for data constructors in suggestion (@garyb)
- Tighten source-spans to token end position (@nwolverson)
- Fix #2042, use JSON for parser errors in rebuild (@paf31)
- Fix some pretty printing issues (@LiamGoodacre)
- Update PSCi `:show import` (@LiamGoodacre)
- Poll to check if the server is running (@kRITZCREEK)
- Update parsec, fixes Number literal parsing #2115 (@hdgarrood)
- Fix #2055, desugar ParensInType inside typed binders (@paf31)
- Make as-patterns bind less tightly (@paf31)
- Fixes #2064 (@kika)
- Fix for issue #2093: Test 'InferRecFunWithConstrainedArgument.purs' contains an unreliable comparison (@andyarvanitis)
- Fix #2092, precedence of type application (@paf31)
- Fix indentation bug #1881 (@DavidLindbom)

## Other

- More portable shebang line in test-everything.sh (@bmjames)
- Add tests for warnings & fix some warnings (@garyb)
- Use Map rather than list in Exports (@garyb)
- Speed up tests by using rebuildModule (@paf31)
- Check that passing tests have a Main module (@hdgarrood)
- Switch to stack for CI, resolves #1974 (@hdgarrood)
- NoImplicitPrelude, enable some global extensions (@garyb)
- Separate the `Op` and `Ident` namespaces, add phantom type for `Op` for values/types (@garyb)
- Multi-file test setup (@garyb)
- Use HSpec for the compiler tests (@garyb)
- New Prelude names in 0.9 (@garyb)

**Comment by garyb** [comment]
I'll definitely need to expand "name resolving" quite a bit to enumerate the various changes there. I'll post something here first then edit it in later :)

**Comment by garyb** [comment]
## Name resolving

The way names are resolved has now been updated in a way that may result in some breakages. The short version is: now only names that have been imported into a module can be referenced, and you can only reference things exactly as you imported them.

Some examples:

Import statement | Exposed members
--- | --- | ---
`import X` | `A`, `f`
`import X as Y` | `Y.A` `Y.f`
`import X (A)` | `A`
`import X (A) as Y` | `Y.A`
`import X hiding (f)` | `A`
`import Y hiding (f) as Y` | `Y.A`

Qualified references like `Control.Monad.Eff.Console.log` will no longer resolve unless there is a corresponding `import Control.Monad.Eff.Console as Control.Monad.Eff.Console`. Importing a module unqualified does not allow you to reference it with qualification, so `import X` does not allow references to `X.A` unless there is also an `import X as X`.

Although the new scheme is stricter it should be easier to understand exactly what the effect of any given import statement is. The old resolution rules for qualified names were obscure and unexpected results could arise when locally-qualified module names overlapped with "actual" module names.

Module re-exports have also been tightened up as a result of these rules. Now if module `X` is only imported `as Y`, the re-export must list `module Y` also. If a module is imported without being re-qualified then the original name is used.

**Comment by paf31** [comment]
I've tested PSCi with various core libraries, so I've checked that off.

**Comment by paf31** [comment]
I'm going to call the release notes done now. We can improve them still, but we have something pretty decent, I think.

**Comment by kRITZCREEK** [comment]
I'll play a bit with psc-ide in a 0.9 project. I think there was one "The impossible happened" related to operators and maybe I can get that fixed today or tomorrow.

**Comment by kRITZCREEK** [comment]
Actually, with the way the new operator aliases work, we have a regression inside `psc-ide`. We currently cannot display type/kind information for operators/type operators.

Fixing this will be a little more involved, so for now I think it's best to display the name of the referenced function/type constructor as the type/kind, so the user can look that value up if he wants to.

**Comment by paf31** [comment]
@kRITZCREEK Could you create an issue for that please?

**Comment by kRITZCREEK** [comment]
#2159

**Comment by paf31** [comment]
@garyb @hdgarrood @kRITZCREEK Is there anything preventing a release of 0.9.1 at this point?

**Comment by kRITZCREEK** [comment]
I think we're good to go :) I tested `psc-ide` as well as I could, but it's currently impossible to find a "big" project that builds with 0.9.0.

So I think we should release 0.9.1, update all the libraries, document bugs or regressions, update the learning material and make 0.9.2 a bugfix release.

**Comment by paf31** [comment]
I've had good results with psc-ide on my project this weekend.

**Comment by garyb** [comment]
I added "Release on npm" to your immediate list, but nope, I think we're good to go.

Has anyone checked if everything with the core RCs compiles together currently?

**Comment by paf31** [comment]
Yes, everything works together, as of a couple of days ago at least.

**Comment by garyb** [comment]
I'm double checking now :)

**Comment by garyb** [comment]
Ok, it's all good, just need to remember to add deprecation notes to:

- `purescript-arrows` (I think we're discontinuing this anyway? If not, it needs updates)
- `purescript-coproducts` (now `purescript-functor-coproducts`)
- `purescript-functors` (now `purescript-functor-products`)

And I need to shake a leg on updating `purescript-datetime`.

**Comment by paf31** [comment]
Does anything use arrows?

**Comment by garyb** [comment]
I think machines provides instances, and maybe some other things do, but I don't think anything _uses_ it. The class is entirely subsumed by things profunctors offer anyway. It just has ArrowZero and ArrowPlus classes too, but no instances.

**Comment by paf31** [comment]
Since we have costrong now, I think we should deprecate it. We might want to deal with ArrowPlus at some point, but I'm not concerned about that right now.

**Comment by hdgarrood** [comment]
I am not sure that Pulp should be checked off just yet, since I haven't managed to do a release yet (sorry). Also, I won't be able to do anything until this weekend, but that shouldn't really require delaying 0.9.1 as far as I can tell. So yeah, I think we're good to go.

**Comment by ethul** [comment]
As a note for webpack, I will follow-up the purescript 0.9.1 release with a compatible version. In terms of time-frame, may be closer to later in the week.

**Comment by paf31** [comment]
Thanks for the update @ethul!

@garyb Perhaps we should move deprecated libraries out into another organization? Bower should still resolve them, as long as we use GitHub to move them.

**Comment by garyb** [comment]
@paf31 I've made [an org for that](https://github.com/purescript-deprecated) and invited you. Just moved the old `purescript-monad-eff` over so far, as that already had a notice. I'll make PRs for notices for the others.

**Comment by garyb** [comment]
@paf31 Should we make a `purescript-kleisli` for `Kleisli` and `Cokleisli`? They're in `purescript-arrows` currently. Alternatively we could provide category instances for `Star` and `Costar` for the same behaviours, but I don't know if that's acceptable from a correctness point of view.

**Comment by paf31** [comment]
I think we would be fine to add the `Category` instances to `profunctors`. I'm less sure about what to do with the `Choice` instance for `CoKleisli` since it uses `Traversable` in place of `Comonad` in Haskell's `profunctors`. It is marked as "highly questionable", but I'm not sure if there is some distinction between `(Co)Star` and `(Co)Kleisli` that I'm missing.

**Comment by paf31** [comment]
@garyb I think we can tag a release today, when you're happy with the core libraries. Just let me know.

**Comment by paf31** [comment]
Now that 0.9.1 is out, contrib authors should please try to get their libraries up to date and released.

cc @cdepillabout @ethul @jdegoes @joneshf @garyb 

Thanks!

**Comment by joneshf** [comment]
Will take a look at what needs to happen tonight. Thanks for the heads up!

**Comment by cdepillabout** [comment]
@paf31 Thanks for the heads up!

[purescript-unicode](https://github.com/purescript-contrib/purescript-unicode) is indirectly using `purescript-aff`, so it's blocked by https://github.com/slamdata/purescript-aff/pull/55.

I'll update `purescript-unicode` when purescript-aff is updated for 0.9.1.

**Comment by joneshf** [comment]
Is there a unified way to build libraries now? Much has changed since I was active.

**Comment by paf31** [comment]
@joneshf Generally, I'd say Pulp, but it's not been updated for 0.9.1 yet (should be this weekend hopefully).

For now, I'm using `psc` directly, which is a bit simpler now:

```
psc 'bower_components/purescript-*/src/**/*.purs' 'src/**/*.purs'
```

**Comment by joneshf** [comment]
Thanks!

If it's alright with you, I'd like to wait until pulp is up to date, and use modern build tools. Is there a timeframe for this issue to be finished?

**Comment by spicydonuts** [comment]
I've heard it'll be done this weekend 🙂

**Comment by spicydonuts** [comment]
@garyb I'll have time to work on `purescript-dom` and `purescript-react-dom` some more tonight or tomorrow.  `purescript-dom` depends on `purescript-datetime` as well, so I can do that too while I'm at it.

**Comment by paf31** [comment]
I think I saw @garyb was working on `datetime` so you might want to sync up with him.

**Comment by garyb** [comment]
Yeah, I'm nearly done with it I think. The JavaScript date type will be in a new library that is just a light wrapper around the native API, and then the existing datetime library will be more purescripty.

**Comment by starper** [comment]
What do you think about having two libraries `Node` and `Browser` that implement node and browser APIs as close to specification as possible (the way `purescript-dom` is implemented now) and everything else could be built upon them? Because if you think it is a good idea then I think now it is the best time for it :)

**Comment by paf31** [comment]
Sounds good, but I would like to build them using code generation from some IDL.

**Comment by garyb** [comment]
I don't think it's possible to do purely from IDL, they leave out lots of implementation details that need handling in PS. You could generate a skeleton, but it would need a lot of manual work still.

**Comment by paf31** [comment]
That's true, but I think there is still value there. These are low level libraries after all. It shouldn't matter if the types are coarser than they could be, since we expect other libraries to build on them anyway.

**Comment by hdgarrood** [comment]
I just released pulp 9.0.0.

**Comment by joneshf** [comment]
Lens is working with 0.9.1 now. I think that's the only contrib package I'm maintaining. Let me know if there are others.

**Comment by paf31** [comment]
Thanks @hdgarrood and thanks @joneshf !

**Comment by hdgarrood** [comment]
That's a good point - do we have any way of getting a list of all the contrib packages that a particular person maintains?

**Comment by jasonzoladz** [comment]
Phil and Harry, thanks for all of your hard work.  I'll update tomorrow.

**Comment by garyb** [comment]
I added a task to update Pursuit itself - we had "Update libraries" listed, but at the moment it's not possible to manually upload docs from 0.9.1 either.

**Comment by cdepillabout** [comment]
`purescript-unicode` has been updated to version [1.0.0](https://github.com/purescript-contrib/purescript-unicode/tree/v1.0.0) for PureScript 0.9.1.

**Comment by Risto-Stevcev** [comment]
Do other pursuit packages need to be updated to work with PureScript 0.9.1 (such as purescript-express)?

**Comment by paf31** [comment]
Yes, pretty much everything does.

**Comment by joneshf** [comment]
Are we supposed to be releasing the libraries at 1.0.0+ now?

**Comment by garyb** [comment]
It's not a requirement, we're just doing so as most of the stuff we're releasing is past being experimental at least, and using the full numbering scheme means we can use semver properly.

**Comment by joneshf** [comment]
Gotcha. I'll update to stay in line.

**Comment by kika** [comment]
I think it makes sense to add `purescript-node-express` to the list of Node packages. It is the primary tool to write server-side applications in Purescript. I started updating it for 0.9.1 and currently blocked by `node-fs` which is blocked by `date`.

**Comment by paf31** [comment]
@kika The Node list above is just the things under the `purescript-node` organization, being one of the three PureScript organizations which has some policy for updates after a compiler release.

I'm not trying to track every library right now, but I'm currently working on a list of packages, based on GitHub data, which will allow us to track things like this.

**Comment by garyb** [comment]
- [`purescript-datetime`](https://github.com/purescript/purescript-datetime) has finally been updated.
- [`purescript-js-date`](https://github.com/purescript-contrib/purescript-js-date) now provides the type and interface for native JavaScript dates.
- [`purescript-now`](https://github.com/purescript-contrib/purescript-now) provides an API for fetching the current date/time.

**Comment by paf31** [comment]
We're very close to being able to close this, I think. The remaining libraries are

- `purescript-channels` (@jdegoes - not sure about the status of this one?)
- `purescript-http-headers` (@garyb - similarly, this is marked as a work in progress - is it active?)

After that, the remaining tasks are

- Update the book (@paf31)
- Write a blog post (anyone want to take this?)
- Update Pursuit and migrate data (@hdgarrood - do you have any time to look at this one?)

**Comment by garyb** [comment]
`purescript-http-headers` does need a bit of work - it's used in affjax, but lacking a few things right now. I'll see if I can work on it on the plane tomorrow perhaps.

**Comment by jdegoes** [comment]
@paf31 I'd like to delete channels. coroutines serve the same purpose and are much cleaner.

**Comment by garyb** [comment]
We can move it over to `purescript-deprecated` in that case :)

**Comment by garyb** [comment]
@jdegoes I've moved it over now. If you want me to move it back or want collaborator access to the repo or anything like that just shout and I'll sort it out.

**Comment by paf31** [comment]
@jdegoes Thanks for the update!

**Comment by hdgarrood** [comment]
I will eventually get around to updating pursuit, probably by the end of the week. Also happy to offer guidance for anyone who doesn't want to wait that long and do it themselves instead.

**Comment by jplatte** [comment]
@hdgarrood I'd like to give it a try. Can you ping me on gitter or IRC when you're available?

**Comment by paf31** [comment]
I'm closing this and the 0.9.1 milestone.

Pursuit is updated and running. Search is still broken, and we still need to upload package data, but we can fix those later.

**Comment by jplatte** [comment]
To clarify: The search is broken in a different way than before now. For the last few weeks only package name search worked, not value search (AFAIK for reasons still unknown); now only searching for operators doesn't work, because we nobody has put in the effort to transform operator aliases into Haskell operator declarations for Hoogle to be able to parse them (the real fix here would be to add proper PureScript support to Hoogle though).

**Comment by joneshf** [comment]
Does type search work?

**Comment by paf31** [comment]
No, but there is an open issue for it. I hope to fix it next week.
