### ISSUE TITLE
[psc-ide] Plans to rework the loading process

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2164]
# Reworking psc-ide's loading process/state management

I'm planning to do a major overhaul of how psc-ide loads assets into memory.

## Current situation

We currently only look at the `externs.json` files inside the specified output folder. At the heart of the loading process lies the function `loadModule`:

1. Decode ExternsFile
2. Convert each ExternsDeclaration into a `psc-ide` internal Externsdecl
3. Add the decoded ExternsFile into the server state, indexed by its ModuleName
4. Add the converted Extersdecls into the server state, indexed by their ModuleName

### Benefits of this approach

- Data we save in the internal state is always indexed by a ModuleName. 
- No data "leaks" into other modules and we can easily update stale data for a changed ExternsFile, by calling `loadModule` again.
- Reloading single modules is fast
- Reloading modules is just generally fast because aeson is amazing, and we only need to parse JSON
- We don't have to worry about the order in which we load modules, because there are no inter module dependencies inside the loading process.

### Problems that arise

Every cross-module dependency has to be resolved at query-time rather than loading time. This is currently the case for resolving Reexports, which get build up and resolved for every query from the loaded state. 

With the recent changes to Operators and TypeOperators we have a similiar situation. Because Operators only contain a reference like ´Control.Monad.bind` we cannot return type information for them unless we look up the identifier at query time.

## Planned Features

The features that I am planning to implement in the near future of `psc-ide` are:

- [x] go-to-definition
- [ ] docstrings for identifiers
- [ ] show-usage
- [ ] show instances for typeclasses

Because all of these need access to the parsed AST, `psc-ide` will start accepting globs for sourcefiles and also hold the parsed AST in memory.

- The additional parsing will make loading slower
- having to match AST nodes with declarations in the externs will need additional computation time
- 3 & 4 need cross module access

In order to enable these new features and move the handling of Reexports and Operators into load-time I propose the following changes.

### Stage 1: ExternsFiles and parsed AST's

These correspond directly to entities on disc, and need to be updated via file-watchers

### Stage 2: AST information

This data only needs to be reloaded whenever the sourcefile for a module changes on disc. Here we can still directly map a resource on disc to the loaded data and don't need to track any dependencies for save partial reloads.

- Docstrings for declarations
- Sourcespans for definitions

### Stage 3: Declarations per module

This data needs to be recomputed whenever a sourcefile or externsfile change.

- Reexports are already resolved here
- Sourcespans for declarations still point to the definition site
- Usagesites per identifier
- Typeinformation (resolved for Operators)
- instances per typeclass

## Split the loading process into 2 stages

When a loading command is issued we parse both sourcefiles and externs and return a response. We then spawn worker threads that populate Stage 2 and 3. If we encounter any errors or warnings in these, we store them and return them in a new `messages` field with the next response.

This way we have access to all the loaded modules when we populate Stage 3 which has all the cross-module stuff. Because cache invalidation is super hard we just rebuild Stage 3 on every change, from scratch.

## Things I plan to gain this way

- New Features
- Keep fast load times
- Improved speed for queries
- A more principled approach to state management

I'm putting this out so maybe you can make suggestions, spot inconsistencies or point out holes in my plans. Thanks for reading all the way to the bottom :)

**Comment by paf31** [comment]
This will be closed in 0.9.2, right @kRITZCREEK?

**Comment by kRITZCREEK** [comment]
I'll extract 

- docstrings for identifiers
- show-usage
- show instances for typeclasses

into a psc-ide roadmap issue then? I've almost got the docstring working :)

**Comment by paf31** [comment]
Sounds good, thanks. And cool!

**Comment by kRITZCREEK** [comment]
Got the lovely number #2222 for the psc-ide roadmap :D
