### ISSUE TITLE
[psc-ide] Near future roadmap

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2222]
Features/ that I'm working on/that are planned in the near future for psc-ide:

- [ ] docstrings for identifiers
- [ ] show-usages
- [ ] show instances for typeclasses
- [x] resolve types/kinds for operators

If you've got suggestions or critique feel free to comment on this issue.

**Comment by rvion** [comment]
Would it make sense for psc / psc-ide to implement a similar mechanism as -fdefer-type-errors in haskell for non parsing-related issues ? It would basically tells the compiler to keep typechecking expressions in the presence of errors, if those expressions are not depending of problematic expressions.

As of now, we can't have those 2 errors in the same time:

A|B
|----|----|
| ![image](https://cloud.githubusercontent.com/assets/2150990/16741010/c5a27b32-47a1-11e6-80c1-9375c998298b.png) |  ![image](https://cloud.githubusercontent.com/assets/2150990/16741025/d68aed76-47a1-11e6-8f92-7163055b9de6.png) |

with such a mechanism, it would be possible for psc-ide to report both.

**Comment by paf31** [comment]
@rvion That would need changes in the compiler itself, not just `psc-ide`. I think it would be better tracked in its own issue.

**Comment by texastoland** [comment]
#1868

**Comment by rvion** [comment]
i have one more suggestion, because I really miss one powerfull and __producti__ feature from my Haskell setup. (both ghc-mod and intero suport it)

-------------

When selecting some code, I wish I could send my selection (startLine, startColumn, endLine, endColumn) to psc-ide, and get back the  __span__ (startLine, startColumn, endLine, endColumn) __and the type of the closest enclosing expression__ in real time

![image](https://cloud.githubusercontent.com/assets/2150990/15269839/0efffc1e-1a0c-11e6-810b-133e56baf617.png)
here, I select `" "`, and ghc-mod detect that the smallest enclosing expression is `concat3 "aa" "bb"`that have type `String -> String`. (In light grey is my selection, in dark blue-ish: the `smallest enclosing expression`)

👍  knowing the smallest enclosing expression is needed so ide plugins can add refactoring features such as `refactor expression as a function`

👍  This allow, using nothing but arrow keys, and shift key, to expand the selection (words by words or lines by lines), and see the __AST__ reveal itself progressively, along each intermediate types. That's a very fast way to grasp a big piece of code. (ide plugin writers just have to write a thin rectangle around the smallest expression enclosing your cursor or selection)

👍  this feature has surprising uses, like allowing one to `shift-right` to hover the first letter of a complex function param to get visual feedback of where the ast node corresponding to the first param end.

👍  according to implementation, it could even offer a way to see step by step how each param refine inference, just by slowly extending the selection, and asking psc-ide the type of the smallest enclosing expression.

Here are some more examples (`grey background` is selection, `blue rectangle` is `smallest enclosing ast node`)
Exemple 1 :

<img width="425" alt="capture d ecran 2015-07-29 a 13 16 35" src="https://cloud.githubusercontent.com/assets/2150990/8956263/403654d8-35f4-11e5-8b54-0ae6391dd0bf.png">
<img width="317" alt="capture d ecran 2015-07-29 a 13 16 41" src="https://cloud.githubusercontent.com/assets/2150990/8956262/4034584a-35f4-11e5-85ad-cbb2c7463d82.png">
<img width="263" alt="capture d ecran 2015-07-29 a 13 16 47" src="https://cloud.githubusercontent.com/assets/2150990/8956264/4036df5c-35f4-11e5-9108-d2bd8b67679d.png">
<img width="266" alt="capture d ecran 2015-07-29 a 13 17 00" src="https://cloud.githubusercontent.com/assets/2150990/8956261/40321792-35f4-11e5-8e77-7e8f479e081a.png">

Example 2:

<img width="295" alt="capture d ecran 2015-07-28 a 13 40 01" src="https://cloud.githubusercontent.com/assets/2150990/8956229/ed26f66c-35f3-11e5-82be-eab203fc1083.png">
<img width="258" alt="capture d ecran 2015-07-28 a 13 39 45" src="https://cloud.githubusercontent.com/assets/2150990/8956230/ed2aaa3c-35f3-11e5-816c-983b96018788.png">
<img width="256" alt="capture d ecran 2015-07-28 a 13 39 40" src="https://cloud.githubusercontent.com/assets/2150990/8956232/ed2b2bec-35f3-11e5-920e-1dea3c369093.png">
<img width="260" alt="capture d ecran 2015-07-28 a 13 39 32" src="https://cloud.githubusercontent.com/assets/2150990/8956231/ed2aee2a-35f3-11e5-94c5-927a0f24ee6c.png">

**Comment by garyb** [comment]
I'm not shooting the suggestion down, but interesting! I loathe that feature - popping stuff up in my face all the time :smile:

**Comment by rvion** [comment]
@garyb 

> I loathe that feature 

I'm not sure to understand. Do you speak about:

 1. the -fdefer-type-errors like feature ?
 2. the smallest-enclosing-expression info feature ?
 3. or the fact that people keep popping stuff up in your face all the time


> If you've got suggestions or critique feel free to comment on this issue.

I just wanted to share my 2 cents on that issue :)


FWIW, and I won't insist anymore on that after this message, but my 2 cents are that the ability to query the smallest-enclosing-expression informations really worth it. I totally understand if you don't want to include that in the Near future roadmap (or in the roadmap at all) but I hope the codebase will leave that feature feasible.

**Comment by texastoland** [comment]
> or the fact that people keep popping stuff up in your face all the time

I inferred just 3 which is more UX than CLI 👍

**Comment by garyb** [comment]
Sorry, I was referring to the smallest-enclosing-expression info feature. I turn a lot of stuff off when using the `ghc-mod` plugin.

**Comment by garyb** [comment]
I guess I shouldn't have been that surprised though, I'm sure if it was unpopular it would be removed or disabled by default - just reflecting on the differing feelings people have for tooling features.

**Comment by kRITZCREEK** [comment]
@rvion All these features require more position annotations on the parsed AST. They'd also require me to be able to capture the context at a certain file position and typecheck arbitrary expressions using that environment. Not saying that's not possible, but it's a very ambitious goal and I think we can make smaller steps towards that goal.

I definitely want to implement "extract-function" and "inline-function", but that's more of a "some time in the future" aswell, as that requires both changes to the parser aswell as a pretty printer for arbitrary PS functions. The things I've gathered here are meant to list things that I intend to implement till 0.10.

**Comment by rvion** [comment]
@garyb oh, so I think we misunderstood eah other. My bad, I shouldn't have focused so much on specific UI exemple  ^^ i was only asking for the ability to query infos.

Presentation is an other problem. Actually,  most haskell ide plugins use the 'get-type-of-smallest-encosing-expression' logic when asked specifically to give the type of the selection, but few (if not none) keep spawning stuff all the time each time  you move the cursor. 

I personally just wanted, when approriate, to be able to query the type of some expression in my context, and not just the raw type signature of the single identifier below my cursor. That is what the suggestion was all about.

I turn on the heavy face popping features mostly only when I need to browse other people code, or when I'm in the middle of some lens heavy code full of infix stuff and subtle type inference monsters.

**Comment by rvion** [comment]
@kRITZCREEK understood, thanks for the explanation

**Comment by paf31** [comment]
@kRITZCREEK Can you please break this up, and prioritize the parts into the appropriate milestones?

**Comment by kRITZCREEK** [comment]
I've opened #2349 and #2350. Find usage is on ice for now since I'd like to have `PositionedType` before doing that. None of these are going to happen for 0.10 though since I'm kind of busy atm ;)

**Comment by paf31** [comment]
0.10 will be released tomorrow hopefully, so no worries 😄 

For now, I'm more concerned with bucketing things into:

- 1.0 (we'd like to implement this before 1.0)
- Approved (we'd like to do this at some point)
- Ideas (we're still collecting requirements, or we haven't decided if something is a good idea or not)
- Closed (things which are not good ideas 😄)

**Comment by kRITZCREEK** [comment]
in that case #2351 is now in the Ideas milestone because of a missing requirement
