### ISSUE TITLE
0.11 Release Checklist

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2745]
- Libraries
  - [x] Core (see below)
  - [x] 0.11 package set (https://github.com/purescript/package-sets/releases/tag/psc-0.11.1)
  - [x] `psc-package` release (https://github.com/purescript/psc-package/releases/tag/v0.1.0)
  - [x] Contrib
  - [x] `purescript-node`
  - [x] Update Pursuit and migrate data
- Documentation 
  - [x] Release notes (https://github.com/purescript/purescript/releases/tag/v0.11.0-rc.1)
  - [x] Documentation repo
  - [ ] Website
  - [ ] Blog post
  - [ ] Book
- Testing
  - [x] `psci`
  - [x] `purs ide`
  - [x] `purs publish` (found #2753)
  - [x] `purs docs` (found #2772)
- Releases
  - [x] Compiler binary release
  - [x] Compiler NPM release
  - [x] Try PureScript (https://github.com/purescript/trypurescript/pull/74)
- Tools
  - [x] Pulp (https://github.com/bodil/pulp/issues/264)
  - [ ] Gulp
  - [ ] `purs-loader`
  - [ ] Editor plugins

**Comment by garyb** [comment]
The core libraries are all already "done" this time, just not released. There's a `ps-0.11` branch for every one that needed updating, so once we think everything else is ready I'll run through and release them in sequence, updating the dependencies to use versions again as appropriate.

Should be a bit smoother than the last few times we did this :smile:

**Comment by hdgarrood** [comment]
Is a Pursuit data migration necessary? I don't remember any changes to the JSON format which were not backwards compatible.

**Comment by paf31** [comment]
> Is a Pursuit data migration necessary?

I'm not sure. I just put it there as a reminder to double check.

**Comment by hdgarrood** [comment]
Ok cool. I expect it won't be necessary but having a reminder to double check is definitely a good idea. Regarding Pulp, I don't think there are any breaking changes we need to worry about, since we are shipping wrapper scripts for `psc` etc (although - come to think of it, I guess not everyone will get those, since some people install from Hackage?) I'm still not quite sure how to address switching over, as having both `purs` and `psc` in different locations on people's PATH is going to be quite likely now. I think perhaps we should consider a `purs-version.txt` file in the root directory of a project as a hint to tooling like pulp which version should be used.

**Comment by paf31** [comment]
Well there is a change needed for the new `purs publish`.

**Comment by hdgarrood** [comment]
Oh yes, of course.

**Comment by paf31** [comment]
I think that should be _relatively_ small though, right?

**Comment by hdgarrood** [comment]
Yes, I don't think it should be too hard.

**Comment by paf31** [comment]
I've created a package sets branch that we can use to test things: https://github.com/purescript/package-sets/pull/57

Please let's add new package versions there as we update them for 0.11.

**Comment by paf31** [comment]
@garyb Curious - any reason you used special branch names rather than pre-release tags?

**Comment by shinnn** [comment]
"Compiler binary release" task is marked done, but:

* `win64.tar.gz` is missing.
* `psc-ide-client` is not executable by users. Is it intentional?

    ```
    $ ls -F ps*

    psc*		psc-docs*	psc-ide-client	psc-publish*
    psc-bundle*	psc-hierarchy*	psc-ide-server*	psci*
    ```

**Comment by garyb** [comment]
@paf31 it just seemed like a bit less of a faff, since you can keep pushing changes to the branches (there are some additions that need going in) and then don't have to keep creating new prereleases. Also it preserves `master` as being correct for the currently active compiler, which has tripped people up occasionally in the past.

Just thought I'd give something a bit different a try this time, since our previous few breaking release processes have been not great.

**Comment by paf31** [comment]
Not sure why `win64.tar.gz` is missing, but we'll make sure it's there before the final release.

`psc-ide-client` not being executable is just an oversight, should be easily fixable.

@garyb Makes sense, thanks, just curious.

**Comment by paf31** [comment]
@garyb I think we could release the core libraries with the compiler, and then handle contrib etc. shortly after. That would mean delaying a Try PureScript release, since that depends on some contrib libraries being updated, but I think that's fine.

**Comment by paf31** [comment]
@shinnn `psc-ide-client` is executable in master now, so that'll be fixed in the next release.

**Comment by garyb** [comment]
Core libraries, in useless alphabetical order :wink::

- [ ] [`purescript-arrays`](https://github.com/purescript/purescript-arrays)
- [ ] [`purescript-assert`](https://github.com/purescript/purescript-assert)
- [ ] [`purescript-bifunctors`](https://github.com/purescript/purescript-bifunctors)
- [ ] [`purescript-catenable-lists`](https://github.com/purescript/purescript-catenable-lists)
- [ ] [`purescript-console`](https://github.com/purescript/purescript-console)
- [ ] [`purescript-const`](https://github.com/purescript/purescript-const)
- [ ] [`purescript-contravariant`](https://github.com/purescript/purescript-contravariant)
- [ ] [`purescript-control`](https://github.com/purescript/purescript-control)
- [ ] [`purescript-datetime`](https://github.com/purescript/purescript-datetime)
- [ ] [`purescript-distributive`](https://github.com/purescript/purescript-distributive)
- [ ] [`purescript-eff`](https://github.com/purescript/purescript-eff)
- [ ] [`purescript-either`](https://github.com/purescript/purescript-either)
- [ ] [`purescript-enums`](https://github.com/purescript/purescript-enums)
- [ ] [`purescript-exceptions`](https://github.com/purescript/purescript-exceptions)
- [ ] [`purescript-exists`](https://github.com/purescript/purescript-exists)
- [ ] [`purescript-foldable-traversable`](https://github.com/purescript/purescript-foldable-traversable)
- [ ] [`purescript-foreign`](https://github.com/purescript/purescript-foreign)
- [ ] [`purescript-free`](https://github.com/purescript/purescript-free)
- [ ] [`purescript-functions`](https://github.com/purescript/purescript-functions)
- [ ] [`purescript-functors`](https://github.com/purescript/purescript-functors)
- [ ] [`purescript-generics-rep`](https://github.com/purescript/purescript-generics-rep)
- [ ] [`purescript-generics`](https://github.com/purescript/purescript-generics)
- [ ] [`purescript-globals`](https://github.com/purescript/purescript-globals)
- [ ] [`purescript-graphs`](https://github.com/purescript/purescript-graphs)
- [ ] [`purescript-identity`](https://github.com/purescript/purescript-identity)
- [ ] [`purescript-inject`](https://github.com/purescript/purescript-inject)
- [ ] [`purescript-integers`](https://github.com/purescript/purescript-integers)
- [ ] [`purescript-invariant`](https://github.com/purescript/purescript-invariant)
- [ ] [`purescript-lazy`](https://github.com/purescript/purescript-lazy)
- [ ] [`purescript-lists`](https://github.com/purescript/purescript-lists)
- [ ] [`purescript-maps`](https://github.com/purescript/purescript-maps)
- [ ] [`purescript-math`](https://github.com/purescript/purescript-math)
- [ ] [`purescript-maybe`](https://github.com/purescript/purescript-maybe)
- [ ] [`purescript-monoid`](https://github.com/purescript/purescript-monoid)
- [ ] [`purescript-newtype`](https://github.com/purescript/purescript-newtype)
- [ ] [`purescript-nonempty`](https://github.com/purescript/purescript-nonempty)
- [ ] [`purescript-orders`](https://github.com/purescript/purescript-orders)
- [ ] [`purescript-parallel`](https://github.com/purescript/purescript-parallel)
- [ ] [`purescript-partial`](https://github.com/purescript/purescript-partial)
- [ ] [`purescript-prelude`](https://github.com/purescript/purescript-prelude)
- [ ] [`purescript-profunctor`](https://github.com/purescript/purescript-profunctor)
- [ ] [`purescript-proxy`](https://github.com/purescript/purescript-proxy)
- [ ] [`purescript-psci-support`](https://github.com/purescript/purescript-psci-support)
- [ ] [`purescript-quickcheck`](https://github.com/purescript/purescript-quickcheck)
- [ ] [`purescript-random`](https://github.com/purescript/purescript-random)
- [ ] [`purescript-refs`](https://github.com/purescript/purescript-refs)
- [ ] [`purescript-semirings`](https://github.com/purescript/purescript-semirings)
- [ ] [`purescript-sets`](https://github.com/purescript/purescript-sets)
- [ ] [`purescript-st`](https://github.com/purescript/purescript-st)
- [ ] [`purescript-strings`](https://github.com/purescript/purescript-strings)
- [ ] [`purescript-symbols`](https://github.com/purescript/purescript-symbols)
- [ ] [`purescript-tailrec`](https://github.com/purescript/purescript-tailrec)
- [ ] [`purescript-transformers`](https://github.com/purescript/purescript-transformers)
- [ ] [`purescript-tuples`](https://github.com/purescript/purescript-tuples)
- [ ] [`purescript-type-equality`](https://github.com/purescript/purescript-type-equality)
- [ ] [`purescript-typelevel-prelude`](https://github.com/purescript/purescript-typelevel-prelude)
- [ ] [`purescript-unfoldable`](https://github.com/purescript/purescript-unfoldable)
- [ ] [`purescript-unsafe-coerce`](https://github.com/purescript/purescript-unsafe-coerce)
- [ ] [`purescript-validation`](https://github.com/purescript/purescript-validation)

**Comment by paf31** [comment]
Contrib:

- [ ] handlebars
- [ ] js-timers
- [ ] react
- [ ] sammy
- [ ] nullable
- [ ] lens
- [ ] unicode
- [ ] form-urlencoded
- [ ] http-methods
- [ ] machines
- [ ] media-types
- [ ] now
- [ ] string-parsers
- [ ] these
- [ ] freet
- [ ] js-date
- [ ] dom
- [ ] jquery
- [ ] options
- [ ] coroutines
- [ ] parsing
- [ ] profunctor-lenses
- [ ] react-dom
- [ ] react-addons-css-transition-group
- [ ] strongcheck
- [ ] arraybuffer-types
- [ ] canvas
- [ ] drawing
- [ ] argonaut-core
- [ ] argonaut-codecs
- [ ] argonaut-traversals
- [ ] argonaut
- [ ] aff-coroutines

Node:

- [ ] node-path
- [ ] node-buffer
- [ ] node-url
- [ ] posix-types
- [ ] node-streams
- [ ] node-fs
- [ ] node-child-process
- [ ] node-process
- [ ] node-http
- [ ] node-readline
- [ ] node-fs-aff

**Comment by sudhirvkumar** [comment]
@paf31 @garyb 

Thank you for all the hard work. As a token of appreciation I would like to help you update the packages in contrib and node for 0.11

I can follow what @garyb has done with the core libraries and send PR for each of the libraries. Please let me know.

**Comment by sudhirvkumar** [comment]
@paf31 @garyb looks like following PR's Checks / CI is working and are merge able.

https://github.com/purescript/purescript-orders/pull/6

https://github.com/purescript/purescript-foreign/pull/60

**Comment by paf31** [comment]
Package set is available, containing the core packages only: https://github.com/purescript/package-sets/releases/tag/psc-0.11.1

Contrib maintainers, assemble!

**Comment by natefaubion** [comment]
FWIW, most library usage of `pulp` is trivial and can be replaced with very basic npm scripts https://github.com/slamdata/purescript-aff/pull/92/commits/2fb1be905bc4bccbf8a5b0a8e53551ef3556521d

**Comment by Pauan** [comment]
Within the next couple days I'll check to make sure that `rollup-plugin-purs` is compatible with 0.11

**Comment by paf31** [comment]
Pursuit and Try PureScript have been updated, with some caveats:

- Try PureScript is running 0.11.1 for the core libraries but continues to run 0.10.7 for things like Try Flare and Try Thermite. Those will be updated separately once the necessary libraries have been updated.
- Pursuit has been updated and I have verified that it accepts new uploads, but many of the existing packages give 500 pages, probably due to data stored in the old format. Search also seems to be broken. So I will roll back that deployment until we are ready to upload all of the core package documentation at least, at which point I will clear out the existing data.

**Comment by paf31** [comment]
Just a handful of contrib dependencies to update now:

- lens
- these
- react-addons-css-transition-group
- argonaut-core
- argonaut-codecs
- argonaut-traversals
- argonaut
- argonaut-strongcheck
- base
- precise

I plan to update the package sets repo and redeploy Pursuit soon, at which point I'll close this and the 0.11 milestone.

**Comment by garyb** [comment]
That's contrib all done apart from `base` now.

**Comment by paf31** [comment]
Thanks @garyb, I've put a package set together, and I'll be working on updating Pursuit today. Then I'll close the milestone.

**Comment by paf31** [comment]
I think we should also update the NPM package and Pulp so we don't need to use `@next` at that point.

**Comment by garyb** [comment]
Yeah, I was thinking we could make v0.11.3 the the `latest` tag for npm, once that has been made, and the update pulp accordingly too :)

**Comment by paf31** [comment]
0.11.3 is tagged: https://github.com/purescript/purescript/releases/tag/v0.11.3

**Comment by garyb** [comment]
:+1:

Just uploaded the win64 bundle since there's still something funky going on with AppVeyor if I remember rightly.

**Comment by hdgarrood** [comment]
I've updated the pulp dist-tag so `npm install pulp` should get you 11.0.0 by default now.

**Comment by Pauan** [comment]
I'm late, but I just now tested `rollup-plugin-purs` with 0.11, and it seems to work fine.

I didn't need to make any changes, because the code output from 0.11 is pretty much the same as 0.10

Here are the file stats for 0.10:

| Bundler            | Unminified | JSMin      | UglifyJS   |
| ------------------ | ---------: | ---------: | ---------: |
| rollup-plugin-purs | `118.4 kB` | `75.5 kB`  | `40.1 kB`  |
| psc-bundle         | `165.3 kB` | `112.2 kB` | `69.2 kB`  |
| webpack            | `944.9 kB` | `639.2 kB` | `176.8 kB` |

And the file stats for 0.11:

| Bundler            | Unminified | JSMin      | UglifyJS   |
| ------------------ | ---------: | ---------: | ---------: |
| rollup-plugin-purs | `112.2 kB` | `70.3 kB`  | `35.7 kB`  |
| purs bundle        | `157.8 kB` | `107.2 kB` | `65.2 kB`  |
| webpack            | `977.4 kB` | `654.0 kB` | `178.8 kB` |

**Comment by ethul** [comment]
Sorry to be so late on this, but a release is out for the `purs-loader` to support 0.11:
https://github.com/ethul/purs-loader/releases/tag/3.0.0-beta.1
