### ISSUE TITLE
Appveyor issues

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#3010]
Just consolidating these under a single issue

- [x] #2774 AppVeyor deployment script fails
- [ ] #2880 AppVeyor CI fails with Access Violation
- [x] #2990 Caching is broken in AppVeyor CI again

**Comment by hdgarrood** [comment]
I looked at GHC trac and saw that a patch for improving Access Violation reporting made it into GHC 8.2.1: https://ghc.haskell.org/trac/ghc/ticket/13108. I'll try updating to GHC 8.2.1 in a branch and see if that sheds any light.

**Comment by hdgarrood** [comment]
[This build](https://ci.appveyor.com/project/hdgarrood/purescript-lfgff/build/2596), which I triggered by pushing to a feature branch, seems to have cleared the cache for the `master` branch, which seems to have fixed the caching issue — all recent builds are completing in 10 minutes or so. I guess AppVeyor must not keep separate caches for separate branches.

**Comment by hdgarrood** [comment]
#2774 should be fixed by https://github.com/purescript/purescript/commit/ee44ff01d217429e210aa143452d52fc137dfc33

**Comment by hdgarrood** [comment]
AppVeyor seems to be working now: https://ci.appveyor.com/project/hdgarrood/purescript-lfgff/history

So I'm going to close this and just hope that it was something which has been fixed since this was opened (either by GHC or by AppVeyor).

**Comment by garyb** [comment]
The deployment stuff still doesn't work, I manually uploaded the windows binaries for the last two releases. I didn't look into why or anything though.

**Comment by hdgarrood** [comment]
Oh ok - I can look into this, thanks for the heads up.
