### ISSUE TITLE
0.12.1 Release Checklist

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#3451]
Commits in master since 0.12: https://github.com/purescript/purescript/compare/v0.12.0...master

# Enhancements

* Print types of missing typeclass members (#3398, @fehrenbach)
* Added `Prim.TypeError.QuoteLabel` for pretty printing labels in custom type errors (#3436, @dariooddenino)
* `purs ide` accepts codegen targets for the rebuild command (#3449, @kRITZCREEK)

# Bugfixes

* Fixes errors spans for `CannotFindDerivingType` (#3425, @kRITZCREEK)
* Fixes a traversal bug where `ObjectNestedUpdate` was surviving desugaring (#3388, @natefaubion)
* Fixes type operators reexports (#3410, @natefaubion) 
* Fixes ST magic-do and inlining (#3444, @natefaubion)
* Fixes missing span information when using do-syntax without importing `bind` or `discard` (#3418, @natefaubion)
* Fixes missing span information when shadowing an open import with a module definition (#3417, @natefaubion)
* Fixes stale `:browse` environment after `:reload` (#3001, @rndnoise)

# Other

* Fix test-support dependency versions and update psci browse test (#3374, @LiamGoodacre) 
* Changes to build with GHC 8.4.3 (#3372, @kRITZCREEK)
* Set --haddock flag based on BUILD_TYPE (#3409, @justinwoo)
* Use `microlens-platform` instead of `lens` (#3400, @joneshf)
* Avoid `Data.ByteString.Lazy.toStrict` (#3433, @coot)
* Add ffiCodegen to MakeActions (#3434, @coot)
* Add nix config to stack.yaml (#3435, @f-f)

**Comment by natefaubion** [comment]
Are there any other PRs we'd like to see land?

* [ ] #3218 Optimize inferred partial constraint fn
* [ ] #3220 Optimize away binds to wildcards in Do notation
* [ ] #3383 Break on symbol constraint
* [ ] #3389 And boolean kind to Prim.Boolean
* [ ] #3411 Row contains
* [ ] #3416 Eliminate built typeclass dicts when necessarily empty
* [ ] #3419 MagicDo desugar forE
* [ ] #3422 MagicDo desugar foreachE
* [ ] #3446 Deriving Hashable

**Comment by JordanMartinez** [comment]
I'm up for a new release whether these additional things are added or not. It'll restart the momentum that has been stalled for a while.

Otherwise, the type-level programming stuff: Boolean kind, Row contains, and break on symbol. Hashable would be nice, too.

**Comment by garyb** [comment]
The only reason things have been stalled is that we've all been busy - making a release won't solve that :wink:

But I think it's fine to release what we have now. @paf31 mentioned a long time ago about releasing on a monthly schedule or something like that, and @joneshf gave some really good reasons for why we should do that - I'm convinced now. The main benefit that I see is it means people know that if they contribute something non-breaking, it's never more than a month away from being released. If nothing changes in that month (or it's just infrastructure or internal stuff that is invisible to a user) then we just skip a release.

It's a bit trickier when it comes to breaking changes, they'll have to be stacked up until we're ready to go or something, but I think we can definitely give it a go and see. We know that there will at least be enough stuff for two months to start with - assuming we release what we have now, and then next month with some of these extra PRs that aren't in yet.

**Comment by thomashoneyman** [comment]
Whether the choice is monthly or something a little longer (a month is really not that much time) I'm so on board with a regular, known-in-advance release schedule.

**Comment by garyb** [comment]
I was just talking with Nate about it a bit on Slack, he raised the same point (a month being rather short) so maybe 6-8 weeks or something. But yeah, a known minimum-time-to-next-release schedule at least.

One of the concerns I had about the idea of a periodic release is that it'd cause stress around release time to try and get everything that was pending in, but I think the way to treat it is just that that's when the release happens - whatever is ready goes in, and no special effort will be made to rush pending things in, as we can always make further releases in between. The idea is there'd be a known minimum time between releases, not that we'd _only_ make releases on a schedule.

I guess we could even do it as a kind of floating schedule - that if we make an intermediate release the "counter" resets, and the next release will be no longer than <period> away.

We probably will have to start actually using branching for breaking changes, but we'll have a little while to figure that out at least as there's nothing breaking "planned" that I can think of right now, aside from the compose inlining change.

**Comment by thomashoneyman** [comment]
It seems fine for the timeline to be a guideline more than something particularly strict -- the main thing is assurance of regular releases, not that on May 15, June 15, and August 15 releases will go out.

With regards to how to manage breaking changes, perhaps some ideas from here are still relevant:
https://discourse.purescript.org/t/how-do-we-avoid-ecosystem-incoherence-in-the-future/209/14

**Comment by joneshf** [comment]
> I guess we could even do it as a kind of floating schedule - that if we make an intermediate release the "counter" resets, and the next release will be no longer than <period> away.

> It seems fine for the timeline to be a guideline more than something particularly strict -- the main thing is assurance of regular releases, not that on May 15, June 15, and August 15 releases will go out.

From a PS-the-library and a PS-the-language user's perspective, adherence to a fairly static schedule has more value to me than anything else. I have no strong thoughts on releases between the scheduled ones. I think they're good and useful, but not necessary. Knowing that on such-and-such date there will be a release, gives me a ton of confidence about: how to plan contributions to the compiler, how to suggest the language to others, what to do about my packages, what to do about my programs, etc.

My suggestion for a schedule is to start by prioritizing what seems reasonable for the people doing the work. Since any schedule is better than none, we (the people not doing the work) should support whatever schedule is chosen. If it's monthly, great. If it's quarterly, great. If it's yearly, great. Whatever y'all think you can do without over-committing, we should support it.

If a few cycles go by and it turns out to be the wrong schedule, we should also support changing it. Setting something like this in stone when it's not been done before feels very risky. But, changing the date every cycle defeats the purpose of having a schedule.

**Comment by JordanMartinez** [comment]
> The only reason things have been stalled is that we've all been busy - making a release won't solve that :wink:

Ah, thanks for correcting me.

**Comment by dariooddenino** [comment]
Just wanted to thank you guys for your work and to say that I support any decision!

I wish I could help with more than trivial issues :)

**Comment by kRITZCREEK** [comment]
I like the idea of having a regular schedule at which we release. It's going to force us to make the release process more ergonomic and will eventually take the edge off. (since it's something we do all the time anyway)

**Comment by sudhirvkumar** [comment]
@garyb How about nightly builds of the master branch? When PR's are merged, nightly build will be useful to test and also don't have to wait for the point or major version release? Of course anybody can build it off the master branch. But everybody will have a reference version (nightly) to discuss if there are bugs or otherwise. Or if somebody is writing a blog post which depends on unreleased features/version of PureScript.

Or do you think it will add too many versions and too much noise rather than useful communication?

Thanks in advance!

**Comment by garyb** [comment]
I'm not sure nightlies would necessarily help - I think the idea is people want to be able to rely on an "agreed upon" public release, and have an expectation of when the next batch of changes might be coming (as per Hardy's comment above). 

A git hash kinda works as well as a nightly version when it comes to blogging about upcoming features - and if we schedule releases at least it could say "In the upcoming [blah] version, due on [date]...", whereas at the moment the release period is entirely random. :smile:

I was going to suggest we try out a 6 week cycle to start with, but I just noticed that that would land the next release on Christmas day, so I'll perhaps tweak that a bit this time 😆. I was going to add a comment to the `README` or `CONTRIBUTING` file about when the next planned release is - any thoughts on where that should live, anyone?

**Comment by thomashoneyman** [comment]
Perhaps we could assign due dates to milestones on a regular schedule (6 weeks) and then keep a persistent note in the readme that releases are made every 6 weeks and to check the latest milestone for the next date.
