### ISSUE TITLE
0.5 Checklist

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#385]
@garyb Let's note everything that we want to get wrapped up before 0.5 here.
- [x] Update the docs
- [x] Move non-core repos over to contrib org
- [x] Get tests running for all core libraries
- [x] README file for every core library
- [x] Make a release for each core library
- [x] Rename all core library source files to `.purs`
- [x] Fix circular dependencies
- [x] Use latest grunt-purescript for all core libraries
- [x] Add `/output/` to `.gitignore` for all core libraries
- [x] Add `/.*` and `!/.gitignore` to `.gitignore` for all core libraries
- [x] Add link to contrib repos on purescript.org

Nice to have:
- [x] Create a `grunt-init` template
- [ ] Update the website / logo

Also, let's make a definitive list of what we consider to be a _core_ library. I think we should try to keep this list pretty short. Here's my thoughts:

Releases:
- [x] [arb-instances](https://github.com/purescript/purescript-arb-instances)
- [x] [arrays](https://github.com/purescript/purescript-arrays)
- [x] [control](https://github.com/purescript/purescript-control)
- [x] [either](https://github.com/purescript/purescript-either)
- [x] [enums](https://github.com/purescript/purescript-enums)
- [x] [exceptions](https://github.com/purescript/purescript-exceptions)
- [x] [foldable-traversable](https://github.com/purescript/purescript-foldable-traversable)
- [x] [foreign](https://github.com/purescript/purescript-foreign)
- [x] [globals](https://github.com/purescript/purescript-globals)
- [x] [math](https://github.com/purescript/purescript-math)
- [x] [maybe](https://github.com/purescript/purescript-maybe)
- [x] [monoid](https://github.com/purescript/purescript-monoid)
- [x] [quickcheck](https://github.com/purescript/purescript-quickcheck)
- [x] [random](https://github.com/purescript/purescript-random)
- [x] [refs](https://github.com/purescript/purescript-refs)
- [x] [strings](https://github.com/purescript/purescript-strings)
- [x] [tuples](https://github.com/purescript/purescript-tuples)
- [x] [validation](https://github.com/purescript/purescript-validation)

Tests:
- [ ] prelude
- [x] [arrays](https://github.com/purescript/purescript-arrays)
- [ ] [control](https://github.com/purescript/purescript-control)
- [x] [either](https://github.com/purescript/purescript-either)
- [x] [enums](https://github.com/purescript/purescript-enums)
- [ ] [exceptions](https://github.com/purescript/purescript-exceptions)
- [ ] [foldable-traversable](https://github.com/purescript/purescript-foldable-traversable)
- [ ] [foreign](https://github.com/purescript/purescript-foreign)
- [x] [globals](https://github.com/purescript/purescript-globals)
- [x] [math](https://github.com/purescript/purescript-math)
- [x] [maybe](https://github.com/purescript/purescript-maybe)
- [ ] [monoid](https://github.com/purescript/purescript-monoid)
- [ ] [random](https://github.com/purescript/purescript-random)
- [ ] [refs](https://github.com/purescript/purescript-refs)
- [x] [strings](https://github.com/purescript/purescript-strings)
- [x] [tuples](https://github.com/purescript/purescript-tuples)
- [ ] [validation](https://github.com/purescript/purescript-validation)
